# Assignment 2: NumPy
- **you will learn:** how to create and manipulate NumPy arrays, perform vectorized computations, and use basic NumPy functions for data analysis
- **task:**  See section 2.9 below
- **deadline:** 20.10.2025
- [NumPy documentation](https://numpy.org/doc/stable/)
- 📝 **Reminder:** Sync your GitHub repository with the main course repository, update your project in PyCharm, and after completing the assignment, commit and push your changes back to GitHub.
---

## 2.0 PEP 8 and Code Commenting

### What is PEP 8?
**PEP 8** is the official **style guide** for Python code.
It defines conventions that make your code **clean, consistent, and easy to read**.
While not mandatory, following PEP 8 is considered a sign of **professional and readable coding**.

### Some Important PEP 8 Rules
- ✅ **Line length:** keep lines **under 79 characters**.
- ✅ **Spacing:**
  - add spaces around operators (`a + b`, not `a+b`)
  - add a space **after** commas, not before (`[1, 2, 3]`, not `[1 ,2 ,3]`)
- ✅ **Variable and function names:** use lowercase with underscores (`calculate_mean`, not `CalculateMean`).
- ✅ **Class names:** use `CamelCase` (`DataProcessor`).
- ✅ **Imports:** at the top of the file, one per line.
- ✅ **Blank lines:** use two blank lines between functions.

 **Official guide:** [PEP 8 – Style Guide for Python Code](https://peps.python.org/pep-0008/)

### Comments and Docstrings
Comments explain **what** your code does and **why**.
Every function should include a **docstring** — a text enclosed in triple quotes `""" ... """` that briefly describes the function’s purpose, parameters, and return value.

#### Example:

```python
def calculate_mean(values):
    """
    Compute the arithmetic mean of a list of numbers.

    Parameters
    ----------
    values : list of float
        Input numbers.

    Returns
    -------
    float
        The arithmetic mean of the input values.
    """
    if not values:
        return 0.0
    return sum(values) / len(values)



---
## 2.1 What is a NumPy Array?

- In computer programming, an **array** is a structure for storing and retrieving data.
- They are the foundation for **data science, machine learning, and scientific computing** in Python.
- We often visualize an array as a **grid in space**, with each cell storing one element of data.
- Arrays can be **1D (vectors), 2D (matrices), or higher-dimensional (tensors)**.

Most NumPy arrays have some rules:

1. **Homogeneous type:** All elements must be of the same data type.
2. **Fixed size:** Once created, the total size cannot change.
3. **Rectangular shape:** All rows (in 2D arrays) must have the same number of columns — no jagged arrays.

When these conditions are met, NumPy can exploit them to make arrays:

- **Faster** (optimized C loops under the hood)
- **More memory efficient** (contiguous memory storage)
- **More convenient to use** (vectorized operations without explicit loops)

In [62]:
import numpy as np
print(np.__version__)

2.3.3


In [63]:
# Create 1D array (vector)
vector = np.array([10, 20, 30, 40, 50])
print("1D array (vector):", vector)
print("Shape:", vector.shape, "Dtype:", vector.dtype)

# Create 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("2D array (matrix):\n", matrix)
print("Shape:", matrix.shape, "Dtype:", matrix.dtype)

# Vectorized operation: multiply all elements by 2 or square them
matrix2 = 2 * matrix
matrix_sq = matrix ** 2
print("Matrix after multiplying by 2:\n", matrix2)
print("Matrix after squaring by 2:\n", matrix_sq)

1D array (vector): [10 20 30 40 50]
Shape: (5,) Dtype: int64
2D array (matrix):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3) Dtype: int64
Matrix after multiplying by 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Matrix after squaring by 2:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


---
## 2.2 Constructing arrays

There are several mechanisms for creating arrays. Among others:

1. **Conversion from other Python structures**
   Arrays can be created directly from existing **lists or tuples** using `np.array()`.
   This is the most common and straightforward way to build an array from existing data.

In [64]:
# Conversion from Python structures
a = np.array([1, 2, 3, 4, 5])
b= np.array(((1,0),(0,1)))
c = np.array([([1,2],[2,1]), ([3,1],[1,3])])
print("From list:\n", a)
print("From tuples of tuples:\n", b)
print("From list of tuples or lists:\n", c)

From list:
 [1 2 3 4 5]
From tuples of tuples:
 [[1 0]
 [0 1]]
From list of tuples or lists:
 [[[1 2]
  [2 1]]

 [[3 1]
  [1 3]]]



2. **NumPy array creation functions**
   NumPy provides a set of **built-in constructors** such as `np.zeros`, `np.ones`, `np.arange`, and `np.linspace`
   to generate arrays of a specific shape or with evenly spaced values.

In [65]:
# np.empty(shape, dtype)
# Creates a new array *without initializing* its entries (values are arbitrary).
arr_empty = np.empty((2,3), dtype="int32")
print("np.empty:\n", arr_empty)
print("np.empty type:", arr_empty.dtype)

np.empty:
 [[         0 1072693248          0]
 [1072693248          0 1072693248]]
np.empty type: int32


In [66]:
# np.identity(n)
# Shortcut for creating a square identity matrix (ones on the main diagonal).
arr_identity = np.identity(4)
print("np.identity:\n", arr_identity)

np.identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [67]:
# np.eye(N, M, k)
# Creates a 2D array with ones on the main (or k-th) diagonal, zeros elsewhere.
arr_eye = np.eye(4,4,-1)
print("np.eye:\n", arr_eye)

np.eye:
 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [68]:
# np.ones(shape, dtype)
# Creates an array of given shape filled with ones.
arr_ones = np.ones((2, 4))
print("np.ones:\n", arr_ones)

np.ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [69]:
# np.zeros(shape, dtype)
# Creates an array filled with zeros.
arr_zeros = np.zeros((3, 3))
print("np.zeros:\n", arr_zeros)

np.zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [70]:
# np.full(shape, fill_value)
# Creates an array filled with a specified constant value.
arr_full = np.full((2, 3), fill_value=7)
print("np.full:\n", arr_full)

np.full:
 [[7 7 7]
 [7 7 7]]


In [71]:
# np.empty_like(prototype)
# Creates an uninitialized array with the *same shape and dtype* as another array.
prototype = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
arr_zeros_like = np.zeros_like(prototype)
print("np.empty_like:\n", arr_zeros_like)

# Similarly with np.empty_like(a), np.zeros_like(a), np.full_like(a, fill_value)

np.empty_like:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [72]:
# np.arange([start,] stop[, step,][, dtype])
# Returns evenly spaced values within a given interval.
# Similar to Python's range(), but returns a NumPy array.
arr_arange = np.arange(0, 10, 2, dtype=float)
print("np.arange:\n", arr_arange)

np.arange:
 [0. 2. 4. 6. 8.]


In [73]:
# np.linspace(start, stop[, num, endpoint])
# Returns evenly spaced numbers over a specified interval.
# Unlike arange, it lets you specify the number of samples.
arr_linspace = np.linspace(0, 1, num=5)
print("np.linspace:\n", arr_linspace)

np.linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [74]:
# np.diag(v[, k])
# Construct a diagonal matrix from a 1D array, or extract a diagonal from a 2D array.
v = np.array([1, 2, 3])
arr_diag = np.diag(v)
print("np.diag (construct from 1D):\n", arr_diag)

np.diag (construct from 1D):
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [75]:
# np.tril(m[, k])
# Return the lower triangle of an array (elements above the k-th diagonal are zeroed).
m = np.arange(1, 10).reshape(3, 3)
arr_tril = np.tril(m)
print("np.tril (lower triangle):\n", arr_tril)

# similarly with np.triu(m[, k])

np.tril (lower triangle):
 [[1 0 0]
 [4 5 0]
 [7 8 9]]



3. **Replicating, joining, or mutating existing arrays**
   Arrays can be **copied, concatenated, reshaped, or repeated** to create new ones.
   For example, you can use `np.tile`, `np.concatenate`, or `reshape` for this purpose.

In [76]:
# np.reshape(a, newshape)
# Changes the shape of an array without changing its data.
a = np.arange(6)
print("a:\n", a)
reshaped = np.reshape(a, (3, 2))
print("np.reshape:\n", reshaped)

a:
 [0 1 2 3 4 5]
np.reshape:
 [[0 1]
 [2 3]
 [4 5]]


In [77]:
# a.flatten()
# Flatten a multi-dimensional array into 1D.
a2 = np.array([[1, 2], [3, 4]])
print("a.flatten:\n", a2.flatten())

a.flatten:
 [1 2 3 4]


In [78]:
# np.transpose(a) or a.T
# Swaps axes, e.g., turns rows into columns.
print("np.transpose:\n", np.transpose(a2))

np.transpose:
 [[1 3]
 [2 4]]


In [79]:
# np.swapaxes(a, axis1, axis2)
# Swaps any two axes in a multi-dimensional array.
a3 = np.arange(8).reshape(2, 2, 2)
print("a3:\n", a3)
print("np.swapaxes:\n", np.swapaxes(a3, 0, 2))

a3:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
np.swapaxes:
 [[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [80]:
# np.moveaxis(a, source, destination)
# Moves a given axis to a new position.
a4 = np.zeros((2, 3, 4))
print("np.moveaxis shape:", np.moveaxis(a4, 0, -1).shape)

np.moveaxis shape: (3, 4, 2)


In [81]:
# np.squeeze(a)
# Removes axes of length 1.
a5 = np.zeros((1, 3, 1))
print("a5:\n", a5)
print("np.squeeze shape:", np.squeeze(a5).shape)
print("a5 squeezed:\n", np.squeeze(a5))

a5:
 [[[0.]
  [0.]
  [0.]]]
np.squeeze shape: (3,)
a5 squeezed:
 [0. 0. 0.]


In [82]:
# np.expand_dims(a, axis)
# Adds a new dimension (axis) to the array.
a6 = np.array([1, 2, 3])
print("np.expand_dims shape:", np.expand_dims(a6, axis=0).shape)

np.expand_dims shape: (1, 3)


In [83]:
# np.concatenate((a1, a2, ...), axis)
# Joins arrays along an existing axis.
a7 = np.ones((2, 2))
b7 = np.zeros((2, 2))
print("np.concatenate:\n", np.concatenate((a7, b7), axis=1))

np.concatenate:
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]]


In [84]:
# np.stack((a1, a2, ...), axis)
# Stacks arrays along a new axis.
a8 = np.array([1, 2])
b8 = np.array([3, 4])
print("np.stack:\n", np.stack((a8, b8), axis=0))

np.stack:
 [[1 2]
 [3 4]]


In [85]:
# np.split(a, sections, axis)
# Splits an array into multiple subarrays.
x = np.arange(9)
print("np.split:\n", np.split(x, 3))

np.split:
 [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [86]:
# np.copy(a)
# Creates a deep copy of the array (independent of the original).
a11 = np.array([1, 2, 3])
b11 = a11.copy()
b11[0] = 99
print("Original:", a11, " | Copy:", b11)

Original: [1 2 3]  | Copy: [99  2  3]


In [87]:
# np.astype(dtype)
# Converts array elements to a new type.
a12 = np.array([1, 2, 3])
print("astype to float:\n", a12.astype(float))

astype to float:
 [1. 2. 3.]


In [88]:
# np.clip(a, min, max)
# Limits values to a given range.
a13 = np.array([-1, 0, 2, 5])
print("np.clip:\n", np.clip(a13, 0, 3))

np.clip:
 [0 0 2 3]


In [89]:
# np.where(condition, x, y)
# Selects elements based on a condition.
a14 = np.array([1, 2, 3])
print("np.where (a > 1 -> 100):\n", np.where(a14 > 1, 100, a14))

np.where (a > 1 -> 100):
 [  1 100 100]



4. **Creating Arrays from Other Libraries**

Many Python libraries — such as **SciPy**, **Pandas**, and **OpenCV** — use NumPy `ndarray` objects as a **common format for data exchange**.
These libraries can **create**, **manipulate**, and **interoperate with** NumPy arrays directly.


---
## 2.3 Indexing arrays

Note that Python indexes (unlike for example R) start from 0, not from 1.

### Basic Indexing

In [90]:
# Create a 2D array for demonstration
x = np.arange(1, 13).reshape(3, 4)
print("Array x:\n", x)

# 1. Single element indexing
print("Single element x[1, 2]:", x[1, 2])
print("Same by chained indexing x[1][2]:", x[1][2])

Array x:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Single element x[1, 2]: 7
Same by chained indexing x[1][2]: 7


In [91]:
# 2. If fewer indices than dimensions, returns a subarray (view)
print("x[0] returns first row (view):", x[0])

x[0] returns first row (view): [1 2 3 4]


In [92]:
# 3. Slicing (rows, columns)
print("x[0:2, 1:4] → rows 0 and 1, columns 1 to 3:\n", x[0:2, 1:4])

x[0:2, 1:4] → rows 0 and 1, columns 1 to 3:
 [[2 3 4]
 [6 7 8]]


In [93]:
# 4. Striding with step (convention start:stop:step)
print("x[:, ::2] → all rows, every second column:\n", x[:, ::2])

x[:, ::2] → all rows, every second column:
 [[ 1  3]
 [ 5  7]
 [ 9 11]]


In [94]:
# 5. Using negative indices
print("x[-1, -2]:", x[-1, -2])  # last row, second-last column

x[-1, -2]: 11


In [95]:
# 6. Ellipsis (`...`) and `newaxis` (alias None)
# Ellipsis expands to as many ":" as needed
print("x[..., 2] → same as x[:, 2]:", x[..., 2])

# newaxis introduces a new dimension
y = x[:, 1]  # shape (3,)
y2 = x[:, 1, np.newaxis]  # shape (3,1)
print("y shape:", y.shape, "   y2 shape:", y2.shape)

x[..., 2] → same as x[:, 2]: [ 3  7 11]
y shape: (3,)    y2 shape: (3, 1)


- All slicing operations produce views, not copies — they refer to the same underlying data.
- Because of this, modifying a slice will affect the original array.
- When using integer indexing (not slicing), you reduce a dimension.
- : means “select all elements along this axis”.
- ... is a convenient placeholder to fill in missing : for remaining axes.

### Advanced Indexing

In [96]:
x = np.arange(1, 13).reshape(3, 4)
print("Array x:\n", x)

# 1. Integer array indexing
row_idx = [0, 2]
col_idx = [1, 3]
# Select elements (0,1) and (2,3)
print("x[row_idx, col_idx]:", x[row_idx, col_idx])

# Equivalent as
print("The same as:", np.array([x[0,1],x[2,3]]))

Array x:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x[row_idx, col_idx]: [ 2 12]
The same as: [ 2 12]


In [97]:
# 2. Broadcasting integer indices
# If you supply fewer index arrays or scalars, they broadcast
print("x[row_idx, 2]:", x[row_idx, 2])
print("The same as:", x[[0,2], [2,2]])

x[row_idx, 2]: [ 3 11]
The same as: [ 3 11]


In [98]:
# 3. Boolean masking (Boolean indexing)
mask = x % 2 == 0  # True for even numbers
print("Boolean mask:\n", mask)
print("x[mask] → all even elements:", x[mask])

# Example modification using Boolean mask
x2 = x.copy()
x2[x2 % 2 == 1] = -1
print("x2 with odd elements replaced by –1:\n", x2)

Boolean mask:
 [[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
x[mask] → all even elements: [ 2  4  6  8 10 12]
x2 with odd elements replaced by –1:
 [[-1  2 -1  4]
 [-1  6 -1  8]
 [-1 10 -1 12]]


In [99]:
# 4. Combining basic and advanced indexing
# e.g. select rows 0 and 2, but columns 1:3
print("x[[0, 2], 1:3]:\n", x[[0, 2], 1:3])

x[[0, 2], 1:3]:
 [[ 2  3]
 [10 11]]


---
## 2.4 Array attributes

- Every NumPy array is a Python object of class `numpy.ndarray`.
- Besides storing the actual data, it also stores various attributes that describe its structure and memory layout.

In [100]:
# Let's create a simple 2D array
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print("Type of numpy array object:", type(a))

Type of numpy array object: <class 'numpy.ndarray'>


In [101]:
print("Number of dimensions (ndim):", a.ndim)
print("Shape (rows, columns):", a.shape)
print("Total number of elements (size):", a.size)
print("Data type (dtype):", a.dtype)
print("Size of one element in bytes (itemsize):", a.itemsize)
print("Total size in bytes (nbytes):", a.nbytes)
print("Transposed array (T):\n", a.T)

Number of dimensions (ndim): 2
Shape (rows, columns): (3, 4)
Total number of elements (size): 12
Data type (dtype): int64
Size of one element in bytes (itemsize): 8
Total size in bytes (nbytes): 96
Transposed array (T):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Example explanation:
- ndim   → tells how many axes (dimensions) the array has
- shape  → gives the length of each dimension as a tuple
- size   → total count of elements = product of shape entries
- dtype  → data type of the elements (e.g. int32, float64)
- itemsize → bytes per element, depends on dtype
- nbytes   → total memory used by the array
- T        → shorthand for the transposed view (rows <-> columns)


---
## 2.5 Array methods

- A NumPy ndarray provides many built-in methods that operate on the array or return information about it. Most of these methods return a new array or a computed value derived from the data.

In [102]:
# Create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape the array to 3 rows and 2 columns
reshaped = a.reshape(3, 2)
print("Reshaped array:\n", reshaped)

# Flatten the array to 1D
flattened = a.flatten()
print("\nFlattened array:", flattened)

Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]

Flattened array: [1 2 3 4 5 6]


In [103]:
# --- Max and Min ---
print("Max element:", a.max())                  # ndarray.max()
print("Index of max (flattened):", a.argmax())  # ndarray.argmax()
print("Min element:", a.min())                  # ndarray.min()
print("Index of min (flattened):", a.argmin())  # ndarray.argmin()

Max element: 6
Index of max (flattened): 5
Min element: 1
Index of min (flattened): 0


In [104]:
# --- Rounding ---
arr_float = np.array([[1.234, 2.567], [3.891, 4.456]])
rounded = arr_float.round(1)             # Round to 1 decimal
print("Rounded array:\n", rounded)

Rounded array:
 [[1.2 2.6]
 [3.9 4.5]]


In [105]:
# --- Trace ---
print("Trace (sum of diagonal):", a.trace())  # Sum along main diagonal

Trace (sum of diagonal): 6


In [106]:
# --- Sum, Cumsum, Mean ---
print("Sum of all elements:", a.sum())
print("Cumulative sum along rows:\n", a.cumsum(axis=1))
print("Mean along columns:", a.mean(axis=0))

Sum of all elements: 21
Cumulative sum along rows:
 [[ 1  3  6]
 [ 4  9 15]]
Mean along columns: [2.5 3.5 4.5]


In [107]:
# --- Variance and Standard Deviation ---
print("Variance of all elements:", a.var())
print("Standard deviation:", a.std())

Variance of all elements: 2.9166666666666665
Standard deviation: 1.707825127659933


In [108]:
# --- Logical checks ---
print("All elements > 0?", (a > 0).all())
print("Any element > 5?", (a > 5).any())

All elements > 0? True
Any element > 5? True


---
## 2.6 Arithmetic and linear algebra


In [109]:
# Create example arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Array a:\n", a)
print("Array b:\n", b)


Array a:
 [[1 2]
 [3 4]]
Array b:
 [[5 6]
 [7 8]]


In [110]:
# Addition (elementwise)
print("Addition (a + b):\n", a + b)

# Subtraction (elementwise)
print("Subtraction (a - b):\n", a - b)

# Multiplication (elementwise)
print("Elementwise multiplication (a * b):\n", a * b)

# Division (elementwise)
print("Elementwise division (a / b):\n", a / b)

# Exponentiation (elementwise)
print("Elementwise power (a ** 2):\n", a ** 2)

# Modulo (elementwise)
print("Elementwise modulo (b % a):\n", b % a)

Addition (a + b):
 [[ 6  8]
 [10 12]]
Subtraction (a - b):
 [[-4 -4]
 [-4 -4]]
Elementwise multiplication (a * b):
 [[ 5 12]
 [21 32]]
Elementwise division (a / b):
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Elementwise power (a ** 2):
 [[ 1  4]
 [ 9 16]]
Elementwise modulo (b % a):
 [[0 0]
 [1 0]]


In [111]:
# Matrix multiplication
matmul = a @ b  # or np.matmul(a, b)
print("Matrix multiplication (a @ b):\n", matmul)

# Dot product
dot = np.dot(a[0], b[0])
print("Dot product (np.dot(a[0], b[0])):\n", dot)

# Transpose
print("Transpose of a (a.T):\n", a.T)

# Determinant
det = np.linalg.det(a)
print("Determinant of a:", det)

# Inverse
inv = np.linalg.inv(a)
print("Inverse of a:\n", inv)

# Eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(a)
print("Eigenvalues of a:", eigvals)
print("Eigenvectors of a:\n", eigvecs)

# Norms
norm_a0 = np.linalg.norm(a[0])
print("Frobenius norm of a[0]:", norm_a0)

Matrix multiplication (a @ b):
 [[19 22]
 [43 50]]
Dot product (np.dot(a[0], b[0])):
 17
Transpose of a (a.T):
 [[1 3]
 [2 4]]
Determinant of a: -2.0000000000000004
Inverse of a:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues of a: [-0.37228132  5.37228132]
Eigenvectors of a:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Frobenius norm of a[0]: 2.23606797749979


---
## 2.7 Miscellaneous

**NumPy** provides optimized **mathematical functions** that work directly on entire arrays (`np.array` objects). These functions are implemented in **compiled C code**, which makes them **very fast**. They automatically apply the operation **elementwise** to all elements in the array — this is called **vectorization**.

In [112]:
# These are elementwise functions that operate efficiently on ndarrays.

# Create an example array
a = np.array([0, np.pi/4, np.pi/2, np.pi])
print("Array a:\n", a)

# Elementwise trigonometric functions
print("sin(a):", np.sin(a))

Array a:
 [0.         0.78539816 1.57079633 3.14159265]
sin(a): [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]


In [113]:
b = np.array([1, 2, 3, 4])
print("Array b:\n", b)

# Exponential
print("Exponential (e^b):", np.exp(b))

# Logarithms
print("Natural log (ln(b)):", np.log(b))
print("Log base 10:", np.log10(b))

# Power
print("b cubed:", np.power(b, 3))
c = np.array([1.234, 5.678, -9.1011])

# Round to nearest integer
print("Rounded:", np.round(c))

# Floor and ceiling
print("Floor:", np.floor(c))
print("Ceil:", np.ceil(c))

# Absolute values
print("Absolute values:", np.abs(c))
d = np.array([1, 2, 3, 4, 5])

# Sum/product
print("Sum:", np.sum(d))
print("Product:", np.prod(d))

Array b:
 [1 2 3 4]
Exponential (e^b): [ 2.71828183  7.3890561  20.08553692 54.59815003]
Natural log (ln(b)): [0.         0.69314718 1.09861229 1.38629436]
Log base 10: [0.         0.30103    0.47712125 0.60205999]
b cubed: [ 1  8 27 64]
Rounded: [ 1.  6. -9.]
Floor: [  1.   5. -10.]
Ceil: [ 2.  6. -9.]
Absolute values: [1.234  5.678  9.1011]
Sum: 15
Product: 120


---
## 2.8 Python lists vs NumPy arrays

Python lists are flexible but **slow and memory-inefficient** for numerical computations.
NumPy arrays (`ndarray`) store data in **contiguous memory** and support **vectorized operations**, making them much faster and smaller in memory footprint.

Let's compare both in terms of **execution speed** and **memory usage**.

In [114]:
import time, sys

# Create a large list and a NumPy array
n = 1_000_000
py_list = list(range(n))
np_array = np.arange(n)

# Compare memory usage of both objects
list_mem = sys.getsizeof(py_list) + sum(sys.getsizeof(x) for x in py_list)
array_mem = np_array.nbytes
print(f"Python list memory: {list_mem / 1e6:.2f} MB")
print(f"NumPy array memory: {array_mem / 1e6:.2f} MB")
print(f"Memory ratio (list / array): {list_mem / array_mem:.1f}×")

# Compute 2x Python list
list_start = time.time()
list_result = [x * 2 for x in py_list]
list_end = time.time()
print(f"Python list time: {list_end - list_start:.5f} s")

# Compute 2x NumPy array
array_start = time.time()
array_result = np_array * 2
array_end = time.time()
print(f"NumPy array time: {array_end - array_start:.5f} s")
print(f"Execution speed ratio (list / array): {(list_end - list_start) / (array_end - array_start):.1f}×")

Python list memory: 36.00 MB
NumPy array memory: 8.00 MB
Memory ratio (list / array): 4.5×
Python list time: 0.02274 s
NumPy array time: 0.00161 s
Execution speed ratio (list / array): 14.1×


**Observation:**

- NumPy operations are much faster because they run in optimized C loops rather than Python loops.
- NumPy arrays use far less memory because all elements share the same data type and they are stored in an efficient way

➡️ This demonstrates the two biggest advantages of NumPy:
1. **Vectorization** (no explicit loops)
2. **Efficient memory representation**

---
## 2.9  🏠 Homework: NumPy Arrays in Data Science

### Task Overview
In this assignment, you will practice working with **NumPy arrays** and **mathematical functions** to perform a mini data analysis. You will simulate a small part of a **data preprocessing pipeline** — a common step in data science when dealing with multivariate datasets.

### Your Task

1. **Generate synthetic data:**
   - Create a NumPy array `data` of shape **(100, 10)** — representing 100 samples and 10 features.
   - The values should be drawn from a **normal distribution** with mean = 50 and standard deviation = 10 using
      `np.random.normal(loc=50, scale=10, size=(100, 10))`.
   - Print the shape, data type, and the **first 5 rows** of the array.

2. **Data cleaning:**
   - Replace all values **smaller than 20** or **larger than 80** with `np.nan` (treat them as outliers).
   - Print how many `np.nan` values are now in the array.

3. **Handle missing values:**
   - Compute the **mean of each column** ignoring missing values (`np.nanmean`).
   - Replace all `np.nan` values in each column with that column’s mean.

4. **Data transformation:**
   - **Standardize each column** so that it has mean 0 and standard deviation 1.
   - Create a new array where:
     - all positive standardized values are replaced with their **square roots**,
     - negative values remain unchanged.
   - For the first 5 rows, also compute the **exponential (`np.exp`)** of all standardized values and print the result.

5. **Array indexing and logical operations:**
   - Compute the **75th percentile** for each column.
   - Create a Boolean mask that marks all values above the 75th percentile.
   - Print how many such “high” values there are in total.
   - Replace all values **below the 25th percentile** (computed column-wise) with the 25th percentile value (a simple form of *winsorization*).

6. **Descriptive statistics:**
   - Compute and print for the final cleaned dataset:
     - column-wise **mean**, **median**, **variance**, and **standard deviation**,
     - the **overall mean** of the entire array,
     - and the **minimum and maximum** values per column.

### ✍️ Hints
- Use functions such as `np.mean`, `np.std`, `np.nanmean`, `np.isnan`, `np.where`, `np.percentile`, `np.sqrt`, and `np.exp`.
- Remember to specify the `axis` argument when computing column-wise statistics (`axis=0`).
- Use **vectorized operations** — avoid `for` loops.
- Include **comments or docstrings** to make your code clear and readable.


---
## Your solution:

1) Generate data

In [125]:
data = np.random.normal(loc=50, scale=10, size=(100, 10))

print(
    f"shape:\n{data.shape},\n"
    f"dtype:\n{data.dtype},\n"
    f"first five rows:\n{data[:5]}"
)

shape:
(100, 10),
dtype:
float64,
first five rows:
[[58.51826398 62.17345749 54.62724185 48.16559481 68.10216201 50.90041734
  58.77169542 40.53654916 44.79876295 54.75627011]
 [46.18304568 48.03104968 52.71921552 56.84063102 43.58850876 49.27269134
  51.06237775 57.25036847 45.87116326 57.41836603]
 [45.72949463 58.65110897 57.27716363 48.31938358 51.76897327 44.99827663
  60.25769735 49.35772053 49.46912165 26.77424848]
 [55.06842    37.42534123 44.29470691 56.91683173 35.08564765 44.17260675
  58.22542201 35.19452224 61.4967903  37.07739895]
 [46.21333579 53.13098186 37.79378122 38.39256236 51.70789585 49.20763258
  50.3766307  59.69118285 58.20275521 54.54309333]]


2) Data cleaning: set outliers to NaN

In [129]:
outliers = (data < 20) | (data > 80)
data[outliers] = np.nan
print(f"\nNumber of NaNs after outlier masking: {np.isnan(data).sum()}")


Number of NaNs after outlier masking: 1


3) Handle missing: fill NaN with column means

In [131]:
col_means = np.nanmean(data, axis=0)
inds = np.where(np.isnan(data))
data[inds] = np.take(col_means, inds[1])

4) Data transformation

In [134]:
mean = data.mean(axis=0)
std = data.std(axis=0, ddof=0)
std_safe = np.where(std == 0, 1, std)
Z = (data - mean) / std_safe

# Transform: sqrt on positives, negatives unchanged
Z_transformed = np.where(Z > 0, np.sqrt(Z), Z)

# First 5 rows: exponential of standardized values
Z_exp_first5 = np.exp(Z[:5])
print(f"\nexp(Z) for first five rows:\n{Z_exp_first5}")


exp(Z) for first five rows:
[[2.33377383 3.51511249 1.54391727 0.67720502 6.04495684 1.21364114
  2.67552048 0.42124019 0.73755965 1.79459637]
 [0.62942321 0.83370416 1.2467387  1.63732868 0.52819735 1.03543276
  1.15588009 2.02385027 0.82883185 2.32069788]
 [0.59981462 2.45636589 2.07766157 0.68788725 1.19140986 0.68235542
  3.14533024 0.96446911 1.22592661 0.1203272 ]
 [1.6176763  0.28337727 0.48508862 1.65007528 0.22678215 0.62954414
  2.5210447  0.25507217 4.53683993 0.32545547]
 [0.63145189 1.40077599 0.23413823 0.25048151 1.1841961  1.02888135
  1.07273081 2.54520876 3.17040925 1.75802833]]


/var/folders/vk/k871hgl904j54ltbrfxw62_c0000gn/T/ipykernel_16493/4100332716.py:7: RuntimeWarning: invalid value encountered in sqrt
  Z_transformed = np.where(Z > 0, np.sqrt(Z), Z)


6) Descriptive statistics on final cleaned dataset

In [136]:
p25 = np.percentile(Z, 25, axis=0)
Z_winsor = np.where(Z < p25, p25, Z)

final_data = Z_winsor

col_mean = final_data.mean(axis=0)
col_median = np.median(final_data, axis=0)
col_var = final_data.var(axis=0, ddof=0)
col_std = final_data.std(axis=0, ddof=0)
overall_mean = final_data.mean()
col_min = final_data.min(axis=0)
col_max = final_data.max(axis=0)

print("\nDescriptive stats (column-wise):")
print("mean:\n", col_mean)
print("median:\n", col_median)
print("variance:\n", col_var)
print("std:\n", col_std)
print("\nOverall mean:", overall_mean)
print("\nmin per column:\n", col_min)
print("max per column:\n", col_max)


Descriptive stats (column-wise):
mean:
 [0.15845219 0.15403307 0.15177234 0.15270562 0.1403331  0.15758026
 0.16195914 0.13189278 0.14537239 0.18902175]
median:
 [-0.08545207  0.02389745 -0.06240051  0.10519142 -0.01442263 -0.00886852
  0.06614921 -0.12876803 -0.08504836  0.04308095]
variance:
 [0.62979055 0.59864589 0.62942908 0.61900308 0.65631567 0.6369053
 0.57670683 0.67449081 0.63080959 0.51827215]
std:
 [0.79359344 0.7737221  0.79336567 0.78676749 0.81013312 0.79806347
 0.75941216 0.8212739  0.79423523 0.71991121]

Overall mean: 0.15431226601704356

min per column:
 [-0.63055481 -0.68752985 -0.6043759  -0.72028573 -0.68170606 -0.59855995
 -0.66171949 -0.67013063 -0.66259042 -0.60301882]
max per column:
 [2.16567546 2.36016044 3.22510216 2.53829734 2.76178169 2.80665976
 2.2982797  2.46219626 2.19345951 1.7770513 ]
